import type { Metadata } from "next";
import { parkinsans } from "./fonts/fonts";
import "./globals.css";
import Navbar from "@/ui/menu/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${parkinsans.variable} font-parkinsans antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
